Java app docker build workflow
on:
push:
paths:
-""app-java/**"


jobs:
docker:
runs-on:ubuntu-latest

steps:
-name:checkout code
uses:action/checkout@v4

-name: login to docker hub
uses: docker/login-action@v2
with:
username:${{secrets.docker-username}}
password:${{secrets.docker-token}}

-name: build docker image
run:docker build -t ${{secrets.docker-username}}/java-asg-app:${{github.sha}} ./app-java

-name: push docker image
run:
docker push ${{secrets.docker-username}}/java-asg-app:${{github.sha}}
docker push ${{secrets.docker-username}}/java-asg-app:latest
