name: terraform validation
on:
push:
branches:["main"]
paths:
-"*.tf"
-"github/workflows/terraform.yml"

jobs:
terraform:
runs-on: ubuntu-latest

steps:

-name: checkout repository
uses: actions/checkout@v4

-name: setup terraform
uses: hashicorp/set-up terraform@v3
with:
 terraform-version: 1.6.6

 -name: terraform format checkout
 run: terraform fmt -check

 -name: configure aws crentials
 uses: aws-actions/configure-aws-credentials@v4
 with: 
 aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID_}}
 aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
 aws-region: ap-south-1

 -name: terraform init
 run: terraform init -input=false

 -name: terraform validate
 run: terraform validate

 -name: terraform plan 
 run: terraform plan -input=false